### Question 1

A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.



null hypothesis=diameter are equal,alternative hypothesis=diameter are not equal
,alpha = 5%

In [1]:
import pandas as pd
import scipy 
import numpy as np
from scipy import stats

In [2]:
cutlets = pd.read_csv("E:\\EXCELR\\PARTH SIR\\inclass excercises\\datasets\\Cutlets.csv")

In [3]:
unita=cutlets.iloc[:,:1]
unitb=cutlets.iloc[:,1:]

In [4]:
p_value=stats.ttest_ind(unita,unitb)
p_value



Ttest_indResult(statistic=array([0.72286887]), pvalue=array([0.47223947]))

In [5]:
p_value[1]

array([0.47223947])

comparing p_value with α = 0.05 (At 5% significance level) we can say that we can continue with null hypothesis

### Question 2

A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
  Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.
 


null hypothesis = there is no difference in the average Turn around time, 
alternative hypothesis = there is difference in the average turn around time, 
alpha = 5 %.

In [6]:
Lab = pd.read_csv("E:\\EXCELR\\PARTH SIR\\inclass excercises\\datasets\\LabTAT.csv")

In [7]:
Lab.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [8]:
#There are more than 2 Population 
p_value = stats.f_oneway(Lab.iloc[:,0],Lab.iloc[:,1],Lab.iloc[:,2],Lab.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [9]:
p_value[1]  #compare it with alpha(0.05)

2.1156708949992414e-57

### Question 3

Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.


In [10]:
BR = pd.read_csv("E:\\EXCELR\\PARTH SIR\\inclass excercises\\datasets\\BuyerRatio.csv")

In [11]:
BR.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [12]:
#there is discrete data present in the dataset so using chi squared test


In [13]:
#making dimension array
obs=np.array([[50,142,131,70],[435,1523,1356,750]])
obs

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [14]:
from scipy.stats import chi2_contingency
p_value=chi2_contingency(obs) # o/p is (Chi2 stats value, p_value, df, expected obsvations)

In [15]:
p_value #compare it with alpha = 0.05

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

### Question 4

TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences



In [16]:
CO = pd.read_csv("E:\\EXCELR\\PARTH SIR\\inclass excercises\\datasets\\Costomer+OrderForm.csv")

In [17]:
CO.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [18]:
CO.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [19]:
CO.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [20]:
CO.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [21]:
CO.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [22]:
values=np.array([[271,267,269,280],[22,33,31,20]])

In [23]:
p_values=chi2_contingency(values)# o/p is (Chi2 stats value, p_value, df, expected obsvations)

In [24]:
p_values #compare it with alpha = 0.05

(4.944234994032096,
 0.17592637125791233,
 3,
 array([[266.96647108, 273.34450964, 273.34450964, 273.34450964],
        [ 26.03352892,  26.65549036,  26.65549036,  26.65549036]]))